# github actions에서 변수를 활용할 수 있는 다양한 방법
name: Variable practice
on:
  push:
    branches: [main]

# on 아래에 env를 위치 시키면 글로별 변수로 활용할 수 있다.

env:
  GLOBAL_COLOR: black

# steps에서 변수를 활용하려면 먼저 실행 단계에 id를 부여하고, 필요한 곳에서 env로 불러올 수 있다.
# multiline 변수를 활용하기 위해서는 delimiter를 활용한다. 보통 EOF를 밚이 사용한다.
# {name}<<{delimiter}
# {value}
# {delimiter}
jobs:
  target:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set color
        id: color-selector
        run: |
          echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"

      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: |
          echo "test"
          echo "The global color is $GLOBAL_COLOR"
          echo "The selected color is $SELECTED_COLOR"

      - name: Set multiline color
        id: multiline-color-selector
        run: |
          {
            echo "MULTILINE_COLOR<<EOF"
            echo "black"
            echo "green"
            echo "red"
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Get multiline color
        env:
          MULTILINE_COLOR: ${{ steps.multiline-color-selector.outputs.MULTILINE_COLOR }}
        run: echo "$MULTILINE_COLOR"
