name: Commit
on:
  push:
    branches: [main]

jobs:
  secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print Commit Message
        run: |
          echo ${{ github.event.head_commit.message }}

      - name: If includes [dev]
        if: contains(${{ github.event.head_commit.message }}, '[dev]')
        run: |
          echo "Include Commit Message"
