# secrets는 공개 할 수 없는 변수를 저장하는 공간이다.
# 저장소의 settings -> Secrets and variables -> Actions에서 등록할 수 있다.
# secrets는 출력하더라도 실행 결과로 노출되지 않는다.

name: Directory
on:
  push:
    branches: [main]

jobs:
  secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: ls
        run: |
          pwd
          ls
