name: pwd
on:
  push:
    branches: [main]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: pwd
        env:
          GITHUB_ACTION_PATH: ${{ github.action_path}}
        run: |
          pwd
          echo $GITHUB_ACTION_PATH
