name: pwd
on:
  push:
    branches: [main]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: pwd
        run: |
          pwd
          echo ${{ github.action_path }}
