name: Target Directory
on:
  push:
    branches: [main]
    paths:
      - 'target-directory/**'

jobs:
  target:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: target hello
        run: echo "pushed target directory"
